# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake

# The command to remove a file.
RM = /nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/Caesar-Cipher-1-comp-339-439-ds-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/Caesar-Cipher-1-comp-339-439-ds-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/nix/store/cbxqzxwlga5pm9rk8qa8fgv5387r540l-cmake-3.19.7/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/Caesar-Cipher-1-comp-339-439-ds-1/CMakeFiles /home/runner/Caesar-Cipher-1-comp-339-439-ds-1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/Caesar-Cipher-1-comp-339-439-ds-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named decoder-test

# Build rule for target.
decoder-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decoder-test
.PHONY : decoder-test

# fast build rule for target.
decoder-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder-test.dir/build.make CMakeFiles/decoder-test.dir/build
.PHONY : decoder-test/fast

#=============================================================================
# Target rules for targets named decoder.exe

# Build rule for target.
decoder.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decoder.exe
.PHONY : decoder.exe

# fast build rule for target.
decoder.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder.exe.dir/build.make CMakeFiles/decoder.exe.dir/build
.PHONY : decoder.exe/fast

#=============================================================================
# Target rules for targets named encoder.exe

# Build rule for target.
encoder.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 encoder.exe
.PHONY : encoder.exe

# fast build rule for target.
encoder.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.exe.dir/build.make CMakeFiles/encoder.exe.dir/build
.PHONY : encoder.exe/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/decoder-test.o: src/decoder-test.cpp.o

.PHONY : src/decoder-test.o

# target to build an object file
src/decoder-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder-test.dir/build.make CMakeFiles/decoder-test.dir/src/decoder-test.cpp.o
.PHONY : src/decoder-test.cpp.o

src/decoder-test.i: src/decoder-test.cpp.i

.PHONY : src/decoder-test.i

# target to preprocess a source file
src/decoder-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder-test.dir/build.make CMakeFiles/decoder-test.dir/src/decoder-test.cpp.i
.PHONY : src/decoder-test.cpp.i

src/decoder-test.s: src/decoder-test.cpp.s

.PHONY : src/decoder-test.s

# target to generate assembly for a file
src/decoder-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder-test.dir/build.make CMakeFiles/decoder-test.dir/src/decoder-test.cpp.s
.PHONY : src/decoder-test.cpp.s

src/decoder.o: src/decoder.cpp.o

.PHONY : src/decoder.o

# target to build an object file
src/decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder.exe.dir/build.make CMakeFiles/decoder.exe.dir/src/decoder.cpp.o
.PHONY : src/decoder.cpp.o

src/decoder.i: src/decoder.cpp.i

.PHONY : src/decoder.i

# target to preprocess a source file
src/decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder.exe.dir/build.make CMakeFiles/decoder.exe.dir/src/decoder.cpp.i
.PHONY : src/decoder.cpp.i

src/decoder.s: src/decoder.cpp.s

.PHONY : src/decoder.s

# target to generate assembly for a file
src/decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder.exe.dir/build.make CMakeFiles/decoder.exe.dir/src/decoder.cpp.s
.PHONY : src/decoder.cpp.s

src/encoder.o: src/encoder.cpp.o

.PHONY : src/encoder.o

# target to build an object file
src/encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.exe.dir/build.make CMakeFiles/encoder.exe.dir/src/encoder.cpp.o
.PHONY : src/encoder.cpp.o

src/encoder.i: src/encoder.cpp.i

.PHONY : src/encoder.i

# target to preprocess a source file
src/encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.exe.dir/build.make CMakeFiles/encoder.exe.dir/src/encoder.cpp.i
.PHONY : src/encoder.cpp.i

src/encoder.s: src/encoder.cpp.s

.PHONY : src/encoder.s

# target to generate assembly for a file
src/encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.exe.dir/build.make CMakeFiles/encoder.exe.dir/src/encoder.cpp.s
.PHONY : src/encoder.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder-test.dir/build.make CMakeFiles/decoder-test.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder.exe.dir/build.make CMakeFiles/decoder.exe.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.exe.dir/build.make CMakeFiles/encoder.exe.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder-test.dir/build.make CMakeFiles/decoder-test.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder.exe.dir/build.make CMakeFiles/decoder.exe.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.exe.dir/build.make CMakeFiles/encoder.exe.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder-test.dir/build.make CMakeFiles/decoder-test.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decoder.exe.dir/build.make CMakeFiles/decoder.exe.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.exe.dir/build.make CMakeFiles/encoder.exe.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... decoder-test"
	@echo "... decoder.exe"
	@echo "... encoder.exe"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/decoder-test.o"
	@echo "... src/decoder-test.i"
	@echo "... src/decoder-test.s"
	@echo "... src/decoder.o"
	@echo "... src/decoder.i"
	@echo "... src/decoder.s"
	@echo "... src/encoder.o"
	@echo "... src/encoder.i"
	@echo "... src/encoder.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

